version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:13.11.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:ci
      - run: mkdir test-results && mv junit.xml test-results
      #  Please write your tests to subdirectories of your store_test_results path
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  my-workflow:
    jobs:
      - test
